/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#FCFBF8",
        surface: "#FFFFFF",
        "surface-muted": "#F7F4EE",
        "border-subtle": "#E8E2D9",
        "border-strong": "#D5CBBE",
        "text-primary": "#1F2937",
        "text-secondary": "#4B5563",
        "text-tertiary": "#6B7280",
        accent: "#0EA5E9",
        "accent-hover": "#0284C7",
        "accent-active": "#0369A1",
        "accent-ghost": "#E0F2FE",
        "accent-ghost-hover": "#BAE6FD",
        "accent-text": "#FFFFFF",
        success: "#16A34A",
        warning: "#D97706",
        danger: "#DC2626",
        "focus-ring": "#38BDF8",
        overlay: "rgba(15, 23, 42, 0.32)",
        "background-dark": "#0B1220",
        "surface-dark": "#111827",
        "surface-muted-dark": "#1F2937",
        "border-subtle-dark": "#334155",
        "border-strong-dark": "#475569",
        "text-primary-dark": "#F8FAFC",
        "text-secondary-dark": "#CBD5E1",
        "text-tertiary-dark": "#94A3B8",
        "accent-dark": "#38BDF8",
        "accent-hover-dark": "#0EA5E9",
        "accent-active-dark": "#0284C7",
        "accent-ghost-dark": "#0C4A6E",
        "accent-ghost-hover-dark": "#075985",
        "accent-text-dark": "#FFFFFF",
        "success-dark": "#22C55E",
        "warning-dark": "#F59E0B",
        "danger-dark": "#F87171",
        "focus-ring-dark": "#38BDF8",
        "overlay-dark": "rgba(2, 6, 23, 0.56)",
      },
      borderRadius: {
        none: "0px",
        xs: "6px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        pill: "999px",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        "3xl": "40px",
        "4xl": "48px",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
      },
      lineHeight: {
        xs: "16px",
        sm: "20px",
        base: "24px",
        lg: "26px",
        xl: "28px",
        "2xl": "32px",
      },
      opacity: {
        disabled: "0.45",
        muted: "0.72",
        overlay: "0.32",
      },
      zIndex: {
        base: "0",
        dropdown: "10",
        sticky: "20",
        modal: "40",
        toast: "50",
      },
      boxShadow: {
        level0: "0px 0px 0px rgba(15,23,42,0)",
        level1: "0px 1px 2px rgba(15,23,42,0.08)",
        level2: "0px 4px 12px rgba(15,23,42,0.12)",
        level3: "0px 10px 24px rgba(15,23,42,0.16)",
      },
    },
  },
  plugins: [],
};
